export const PAKISTANI_BANKS = [
  'Al Baraka Bank Pakistan',
  'Allied Bank',
  'Askari Bank',
  'Bank Al-Habib',
  'Bank Alfalah',
  'Bank of Khyber',
  'Bank of Punjab',
  'Dubai Islamic Bank Pakistan',
  'Easypaisa',
  'Faysal Bank',
  'First Women Bank',
  'Habib Bank Limited',
  'HBL',
  'JazzCash',
  'JS Bank',
  'Keystone Bank',
  'MCB Bank',
  'Meezan Bank',
  'National Bank of Pakistan',
  'NayaPay',
  'NBP',
  'Neem',
  'SadaPay',
  'Silk Bank',
  'SME Bank',
  'Soneri Bank',
  'Standard Chartered Pakistan',
  'UBL',
  'United Bank Limited',
  'Zarai Taraqiati Bank',
] as const
